package com.streamfirst.iceberg.hybrid.domain;

import java.time.Instant;
import java.util.List;

/**
 * Plan for coordinated garbage collection across on-premise and cloud environments.
 * 
 * <p>This record represents a deletion plan generated by the on-premise GC coordinator
 * and synchronized to the cloud environment. It ensures safe, coordinated cleanup of
 * expired Iceberg data files while respecting safety windows and active queries.
 * 
 * <p>The plan includes temporal validity constraints to prevent execution of stale
 * deletion plans and ensure proper coordination between environments.
 * 
 * <p>Key safety features:
 * <ul>
 * <li>Time-bounded validity window to prevent stale plan execution</li>
 * <li>Generation timestamp for safety window calculations</li>
 * <li>Approval tracking for audit and compliance requirements</li>
 * <li>Per-table scoping to limit blast radius of operations</li>
 * </ul>
 * 
 * @param tableId the table this deletion plan applies to
 * @param deleteCandidates list of object URIs that are candidates for deletion
 * @param generatedAt timestamp when this plan was created (used for safety windows)
 * @param validFrom earliest time this plan can be executed
 * @param validUntil latest time this plan remains valid for execution
 * @param approvals list of approval identifiers required for deletion audit trail
 */
public record DeletePlan(TableId tableId, List<String> deleteCandidates, Instant generatedAt,
                         Instant validFrom, Instant validUntil, List<String> approvals) {}
